version: "3.8"

services:
  api:
    build: ./backend
    container_name: patient_api
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://patient_user:patient_password@db:5432/patient_db 
    volumes:
      - ./backend/:/backend
      - /backend/node_modules
    working_dir: /backend
    command: ["sh", "-c", "wait-for-it db:5432 -- node server.js"]

  frontend:
    build: ./frontend
    container_name: patient_frontend
    ports:
      - "3000:3000"
    depends_on:
      - api
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    working_dir: /frontend
    command: ["npm", "start"]

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: patient_user
      POSTGRES_PASSWORD: patient_password
      POSTGRES_DB: patient_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initPatient.sql:/docker-entrypoint-initdb.d/initPatient.sql 

volumes:
  postgres_data:
