version: "3.8"

services:
  api:
    build: ./backend
    container_name: patient_api
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - NODE_ENV=${NODE_ENV}
      - DATABASE_URL=${DATABASE_URL}
      - SERVER_URL=${SERVER_URL}
      - FRONTEND_URL=${FRONTEND_URL}
    env_file:
      - .env
    volumes:
      - ./backend/:/backend
      - /backend/node_modules
    working_dir: /backend
    command: ["sh", "-c", "sleep 5 && node server.js"]

  frontend:
    build: ./frontend
    container_name: patient_frontend
    ports:
      - "3000:3000"
    depends_on:
      - api
    environment:
      - SERVER_URL=${SERVER_URL}
      - FRONTEND_URL=${FRONTEND_URL}
    env_file:
      - .env
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    working_dir: /frontend
    command: ["npm", "start"]

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
